#cloud-config
packages:
  -curl

runcmd:
  - curl -O "https://c.elum.su/init.sh"
  - chmod +x init.sh
  - sh ./init.sh "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPGT2AHuhMZoVmJ0AxqLnG6/sAnzfGNRzDyc5Z8GvXUe master" "gmelum@vk.com" "elum.su" "shop.anonim"